# .pre-commit-config.yaml
default_language_version:
  python: python3.11

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: check-byte-order-marker
  - id: check-added-large-files

-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
# - repo: https://github.com/ambv/black
#   rev: 22.12.0
#   hooks:
#   - id: black
# - repo: https://github.com/asottile/reorder_python_imports
#   rev: v3.9.0
#   hooks:
#   -   id: reorder-python-imports
# # - repo: https://github.com/charliermarsh/ruff-pre-commit
# #   # Ruff version.
# #   rev: 'v0.0.235'
# #   hooks:
# #     - id: ruff
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.991
#   hooks:
#   - id: mypy
#     name: Run type checks
#     args: ["--ignore-missing-imports", "--install-types", "--non-interactive"]
# # - repo: https://github.com/pycqa/pydocstyle
# #   rev: 6.3.0
# #   hooks:
# #   - id: pydocstyle
# - repo: local
#   hooks:
#   - id: migrations-check
#     language: system
#     name: Check for uncreated migrations.
#     entry: bash -c "./manage.py makemigrations --check --dry-run"
#     types: ["python"]
#     pass_filenames: false
# repos:
#   - repo: https://github.com/PyCQA/pylint.git
#     rev: main
#     hooks:
#       - id: pylint
#         args: ['--exit-zero']

#   - repo: https://github.com/PyCQA/flake8.git
#     rev: main
#     hooks:
#       - id: flake8

#   - repo: https://github.com/timothycrosley/isort.git
#     rev: main
#     hooks:
#       - id: isort

#   - repo: https://github.com/psf/black.git
#     rev: main
#     hooks:
#       - id: black

#   # - repo: https://github.com/datitran/dandelion.git
#   #   rev: main
#   #   hooks:
#   #     - id: dandelion

#   - repo: https://github.com/django/django.git
#     rev: main
#     hooks:
#       - id: django-check
#         args: ['--system-checks']

#   - repo: https://github.com/pytest-dev/pytest.git
#     rev: main
#     hooks:
#       - id: pytest

#   - repo: https://github.com/pytest-dev/pytest-django.git
#     rev: main
#     hooks:
#       - id: pytest-django

#   - repo: https://github.com/PyCQA/bandit.git
#     rev: main
#     hooks:
#       - id: bandit

#   - repo: https://github.com/pyupio/safety.git
#     rev: main
#     hooks:
#       - id: safety

# repos:
#     - repo: local
#         rev: https://github.com/python/mypy.git
#         hooks:
#             - id: mypy
#               args: ['your_app']  # Replace with your app name(s)
# # repos:
#     - repo: local
#         rev: https://github.com/sphinx-user-docs/sphinx-autoapi.git
#         hooks:
#             - id: sphinx-autoapi

# repos:
#     - repo: local
#         rev: https://github.com/PyCQA/pylint.git
#         hooks:
#             - id: pylint
#               args: ['your_app/models.py']  # Check
