name: Build and Publish Images

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Django app image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.django  # Use separate Dockerfiles for each image
          push: true
          tags:  ${{ secrets.DOCKERHUB_USERNAME }}/graduation:latest  # Customize image names
        #   build-args: DJANGO_SETTINGS_MODULE=${{ secrets.DJANGO_SETTINGS_MODULE }}  # Inject secret environment variable

      - name: Build and push Nginx image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx_graduation:latest  # Customize image names


